version: '3'
services:
  neo4j:
    image: neo4j:5.22.0-enterprise
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
    networks:
      - neo4j-net
    # entrypoint: [ "tail", "-f", "/dev/null" ]

networks:
  neo4j-net:
